export const ERR = {
    // Common error (-1 -> -99)
    UNKNOWN: -1,
    UNAUTHORIZED: -2,
    INVALID_ROLE: -3,
    OBJECT_NOT_FOUND: -4,
    INVALID_FORMAT: -5,
    INVALID_VERSION: -6,
    OBJECT_IS_ALREADY_EXIST: -7,
    DATA_MISMATCH: -8,
    INVALID_APIKEY: -9,
    
    // Login (-101 -> -199)
    INVALID_USERNAME_OR_PASSWORD: -101,
    REFRESH_TOKEN_NOT_FOUND: -102,
    REFRESH_TOKEN_IS_EXPIRED: -103,

    // User profile: (-201 -> -299)
    OLD_PASSWORD_WRONG: -201,
    INVALID_PASSWORD_FORMAT: -202,

    // Promotion
    INVALID_RULES_FORMAT: -301,
    INVALID_REWARDS_FORMAT: -302,
    NOT_ENOUGH_CODE_SPACE: -303,
    TRANSACTION_DATA_MISMATCH: -304,
    PROMOTION_CODE_IS_UNUSABLE: -305,
};

export default ERR;